// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VacinasInfantis.Infrastrutura.DataBaseAcesso;

#nullable disable

namespace VacinasInfantis.API.Migrations
{
    [DbContext(typeof(VacinaInfantilDbContext))]
    [Migration("20250323201704_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VacinasInfantis.Domain.Entidades.Criancas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Criancas");
                });

            modelBuilder.Entity("VacinasInfantis.Domain.Entidades.VacinasCriancas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MesAplicacao")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VacinasCriancas");
                });

            modelBuilder.Entity("VacinasInfantis.Domain.Entidades.VacinasTomadas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CriancasId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataTomada")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("VacinasId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CriancasId");

                    b.HasIndex("VacinasId");

                    b.ToTable("VacinasTomadas");
                });

            modelBuilder.Entity("VacinasInfantis.Domain.Entidades.VacinasTomadas", b =>
                {
                    b.HasOne("VacinasInfantis.Domain.Entidades.Criancas", "Criancas")
                        .WithMany()
                        .HasForeignKey("CriancasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VacinasInfantis.Domain.Entidades.VacinasCriancas", "Vacinas")
                        .WithMany()
                        .HasForeignKey("VacinasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criancas");

                    b.Navigation("Vacinas");
                });
#pragma warning restore 612, 618
        }
    }
}
