// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VacinasInfantis.Infrastrutura.DataBaseAcesso;

#nullable disable

namespace VacinasInfantis.API.Migrations
{
    [DbContext(typeof(VacinaInfantilDbContext))]
    partial class VacinaInfantilDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VacinasInfantis.Domain.Entidades.CalendarioDeVacinas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("MesAplicacao")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeDaVacina")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CalendarioDeVacinas");
                });

            modelBuilder.Entity("VacinasInfantis.Domain.Entidades.Criancas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDeNascimentoDaCrianca")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeDaCrianca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDaMae")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDoPai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Criancas");
                });

            modelBuilder.Entity("VacinasInfantis.Domain.Entidades.Profissionais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeProfissional")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("RegistroProfissional")
                        .HasColumnType("bigint");

                    b.Property<string>("UnidadeSaude")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Profissionais");
                });

            modelBuilder.Entity("VacinasInfantis.Domain.Entidades.Vacinas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriancasId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("MesAplicacao")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeDaVacina")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProfissionalSaudeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriancasId");

                    b.HasIndex("ProfissionalSaudeId");

                    b.ToTable("VacinasCriancas");
                });

            modelBuilder.Entity("VacinasInfantis.Domain.Entidades.Vacinas", b =>
                {
                    b.HasOne("VacinasInfantis.Domain.Entidades.Criancas", "Crianca")
                        .WithMany("Vacinas")
                        .HasForeignKey("CriancasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VacinasInfantis.Domain.Entidades.Profissionais", "ProfissionalSaude")
                        .WithMany("Vacinas")
                        .HasForeignKey("ProfissionalSaudeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crianca");

                    b.Navigation("ProfissionalSaude");
                });

            modelBuilder.Entity("VacinasInfantis.Domain.Entidades.Criancas", b =>
                {
                    b.Navigation("Vacinas");
                });

            modelBuilder.Entity("VacinasInfantis.Domain.Entidades.Profissionais", b =>
                {
                    b.Navigation("Vacinas");
                });
#pragma warning restore 612, 618
        }
    }
}
